const BIOS_BRANDS = [
  {
    id: "asus",
    name: "ASUS",
    logo: "A",
    desc: "UEFI BIOS Utility / EZ Mode & Advanced Mode",
    series: ["ROG (Republic of Gamers)", "TUF Gaming", "ProArt", "PRIME", "Dual"],
  },
  {
    id: "msi",
    name: "MSI",
    logo: "M",
    desc: "Click BIOS 5 / Compact BIOS",
    series: ["MEG", "MPG", "MAG", "PRO", "Commercial"],
  },
  {
    id: "gigabyte",
    name: "Gigabyte",
    logo: "G",
    desc: "UEFI BIOS / Easy Mode & Classic Mode",
    series: ["AORUS", "AERO", "Gaming X", "Ultra Durable", "Eagle"],
  },
  {
    id: "asrock",
    name: "ASRock",
    logo: "S",
    desc: "UEFI BIOS / EZ Mode & Advanced Mode",
    series: ["Taichi", "Phantom Gaming", "Steel Legend", "Extreme", "Pro"],
  },
  {
    id: "biostar",
    name: "Biostar",
    logo: "B",
    desc: "UEFI BIOS / Advanced Mode",
    series: ["Racing", "Valence", "Silver", "Classic"],
  },
];

const BIOS_GUIDE = [
  {
    id: "xmp",
    title: "XMP / DOCP / EXPO",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="7" width="20" height="10" rx="1"/><path d="M6 11v2M10 11v2M14 11v2M18 11v2"/></svg>',
    biosPaths: {
      asus: "Ai Tweaker > Ai Overclock Tuner > XMP",
      msi: "OC > Extreme Memory Profile (X.M.P.) > Enabled",
      gigabyte: "Tweaker > Extreme Memory Profile (X.M.P.) > Profile 1",
      asrock: "OC Tweaker > DRAM Configuration > Load XMP Setting",
      biostar: "Overclock > DRAM Configuration > XMP > Enabled",
    },
    description: "Профиль памяти — разгоняет RAM до заявленной производителем частоты, таймингов и напряжения. Без XMP память работает на базовых 2133/4800 МГц.",
    recommended: "Включить XMP Profile 1 (или XMP 2 для второго профиля).",
    risks: "Если система не стабильна после включения — попробуй второй профиль или ручной разгон с увеличением напряжения. Редко требует повышения VCCIO/VCCSA на Intel.",
  },
  {
    id: "resizable_bar",
    title: "Resizable BAR / Above 4G Decoding",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M22 12H2M5 12V6a2 2 0 012-2h10a2 2 0 012 2v6M5 12v6a2 2 0 002 2h10a2 2 0 002-2v-6"/></svg>',
    biosPaths: {
      asus: "Advanced > PCI Subsystem Settings > Above 4G Decoding > Enabled > Re-Size BAR Support > Enabled",
      msi: "Settings > Advanced > PCI Subsystem Settings > Above 4G Decoding > Enabled > Re-Size BAR Support > Enabled",
      gigabyte: "Settings > Miscellaneous > Above 4G Decoding > Enabled > Re-Size BAR Support > Enabled",
      asrock: "Advanced > PCI Configuration > Above 4G Decoding > Enabled > Re-Size BAR Support > Enabled",
      biostar: "Advanced > PCI Configuration > Above 4G Decoding > Enabled > Re-Size BAR Support > Enabled",
    },
    description: "Позволяет CPU обращаться ко всей VRAM видеокарты сразу, а не по 256 МБ блокам. Увеличивает FPS в играх на 5-15%.",
    recommended: "Включить оба параметра. Обновите GPU-драйвер перед активацией.",
    risks: "Может вызвать проблемы на старых GPU (GTX 10xx и ранее). Если игра вылетает — отключите.",
  },
  {
    id: "c_states",
    title: "Отключение C-States",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 2"/></svg>',
    biosPaths: {
      asus: "Advanced > CPU Configuration > CPU - Power Management Control > Intel SpeedStep (EIST) > Disabled > CPU C-States > Disabled",
      msi: "OC > CPU Features > Intel SpeedStep (EIST) > Disabled > C-State Support > Disabled",
      gigabyte: "Tweaker > Advanced CPU Settings > Intel SpeedStep (EIST) > Disabled > CPU C-States Control > Disabled",
      asrock: "Advanced > CPU Configuration > Intel SpeedStep (EIST) > Disabled > CPU C-State Support > Disabled",
      biostar: "Advanced > CPU Configuration > Intel SpeedStep (EIST) > Disabled > CPU C-State > Disabled",
    },
    description: "C-States переводят процессор в режим энергосбережения при простое. Отключение убирает micro-stuttering и снижает input lag в играх.",
    recommended: "Disabled для максимальной производительности. Auto для баланса энергии и производительности.",
    risks: "Повышает энергопотребление и нагрев CPU на 5-15 Вт. Убедитесь, что охлаждение достаточное.",
  },
  {
    id: "power_limits",
    title: "Power Limits (PL1/PL2) / PBO",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M13 2L3 14h9l-1 8 10-12h-9l1-8z"/></svg>',
    biosPaths: {
      asus: "Ai Tweaker > Internal CPU Power Management > Long Duration Power Limit > Max / Short Duration Power Limit > Max",
      msi: "OC > CPU Features > Long Duration Power Limit (W) > 4096 / Short Duration Power Limit (W) > 4096",
      gigabyte: "Tweaker > Advanced CPU Settings > CPU Power Limits > PL1/PL2 > Max",
      asrock: "Advanced > CPU Configuration > Power Limits > PL1/PL2 > Max",
      biostar: "Advanced > CPU Configuration > Power Limits > Max",
    },
    description: "PL1 (Long Duration) и PL2 (Short Duration) лимитируют мощность CPU. Снимая лимиты, даёте процессору работать на полной мощности. Для AMD — PBO (Precision Boost Overdrive) автоматически разгоняет CPU.",
    recommended: "Intel: PL1/PL2 на максимум или Unlimited. AMD: PBO > Enabled, PBO Limits > Motherboard.",
    risks: "Повышение нагрева на 10-20°C. Требуется хорошее охлаждение (минимум башенный кулер/240mm AIO).",
  },
  {
    id: "spread_spectrum",
    title: "Spread Spectrum",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M2 12c2-4 4-4 6 0s4 4 6 0 4-4 6 0"/></svg>',
    biosPaths: {
      asus: "Ai Tweaker > DIGI+ VRM > Spread Spectrum > Disabled",
      msi: "OC > DIGI+ VRM > Spread Spectrum > Disabled",
      gigabyte: "Tweaker > CPU VR Settings > Spread Spectrum > Disabled",
      asrock: "Advanced > CPU Configuration > Spread Spectrum > Disabled",
      biostar: "Advanced > Spread Spectrum > Disabled",
    },
    description: "Spread Spectrum снижает электромагнитные помехи за счёт модуляции тактовой частоты. Для оверклокинга это нестабилизирует частоту и увеличивает задержки.",
    recommended: "Disabled для максимальной стабильности и минимальных задержек.",
    risks: "Незначительно увеличивает EMI. Для большинства пользователей это не проблема.",
  },
  {
    id: "fast_boot",
    title: "Fast Boot",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><polygon points="13 2 3 14 12 14 11 22 21 10 12 10 13 2"/></svg>',
    biosPaths: {
      asus: "Boot > Fast Boot > Enabled (Ultra Fast для максимальной скорости)",
      msi: "Settings > Advanced > Windows OS Configuration > Fast Boot > Enabled",
      gigabyte: "BIOS > Fast Boot > Enabled",
      asrock: "Boot > Fast Boot > Enabled",
      biostar: "Boot > Fast Boot > Enabled",
    },
    description: "Ускоряет загрузку Windows, пропуская часть POST-тестов. Ultra Fast Boot может ускорить загрузку до 5-8 секунд.",
    recommended: "Enabled для баланса скорости и удобства. Ultra Fast — только для SSD и UEFI.",
    risks: "При Ultra Fast Boot может не работать клавиша Del/F2 для входа в BIOS. Используйте BIOS Flashback или Clear CMOS для доступа.",
  },
  {
    id: "boot_priority",
    title: "Приоритет загрузки (Boot Priority)",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 17l6-6-6-6M12 19h8"/></svg>',
    biosPaths: {
      asus: "Boot > Boot Option Priorities > Boot Option #1 > Выберите ваш SSD",
      msi: "Settings > Boot > Boot Option Priorities > Boot Option #1 > Выберите ваш SSD",
      gigabyte: "BIOS > Boot Option Priorities > Boot Option #1 > Выберите ваш SSD",
      asrock: "Boot > Boot Option Priorities > Boot Option #1 > Выберите ваш SSD",
      biostar: "Boot > Boot Option Priorities > Boot Option #1 > Выберите ваш SSD",
    },
    description: "Устанавливает SSD с системой первым в очереди загрузки. Ускоряет загрузку и исключает загрузку с других устройств.",
    recommended: "Boot Option #1 = ваш системный SSD (UEFI: Windows Boot Manager).",
    risks: "Если SSD будет отключён, система загрузится со следующего устройства в списке.",
  },
  {
    id: "sata_mode",
    title: "SATA Mode (AHCI)",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><rect x="2" y="3" width="20" height="14" rx="2"/><path d="M8 21h8M12 17v4"/></svg>',
    biosPaths: {
      asus: "Advanced > SATA Configuration > SATA Mode Selection > AHCI",
      msi: "Settings > Advanced > SATA Mode > AHCI",
      gigabyte: "Settings > IO Ports > SATA Mode > AHCI",
      asrock: "Advanced > SATA Configuration > SATA Mode > AHCI",
      biostar: "Advanced > SATA Configuration > SATA Mode > AHCI",
    },
    description: "AHCI включает NCQ (командная очередь) и горячую замену дисков. IDE/RAID — устаревшие режимы, замедляющие SSD.",
    recommended: "AHCI. Меняйте ТОЛЬКО до установки Windows (или с переустановкой драйверов).",
    risks: "Смена с IDE на AHCI после установки Windows вызовет BSOD. Нужен безопасный режим или реестр-фикс.",
  },
  {
    id: "peripheral_off",
    title: "Отключение неиспользуемой периферии",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><line x1="18" y1="6" x2="6" y2="18"/><line x1="6" y1="6" x2="18" y2="18"/></svg>',
    biosPaths: {
      asus: "Advanced > Onboard Devices Configuration > Отключить неиспользуемые (Audio, LAN, Wi-Fi, Bluetooth, RGB)",
      msi: "Settings > Advanced > Integrated Peripherals > Отключить неиспользуемые",
      gigabyte: "Settings > IO Ports > Отключить неиспользуемые (Audio, LAN, Wi-Fi)",
      asrock: "Advanced > South Bridge > Отключить неиспользуемые",
      biostar: "Advanced > Onboard Devices > Отключить неиспользуемые",
    },
    description: "Отключение встроенных компонентов (аудио, LAN, Wi-Fi, Bluetooth, RGB-контроллеры) снижает потребление IRQ-прерываний и уменьшает задержки ввода.",
    recommended: "Отключайте только то, чем точно не пользуетесь. Не отключайте LAN/Wi-Fi без проводного доступа.",
    risks: "Если отключите сетевой адаптер и нет проводного подключения — потеряете интернет.",
  },
  {
    id: "bios_update",
    title: "Обновление BIOS",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15v4a2 2 0 01-2 2H5a2 2 0 01-2-2v-4M7 10l5 5 5-5M12 15V3"/></svg>',
    biosPaths: {
      asus: "Tool > ASUS EZ Flash 3 Utility > с USB-накопителя",
      msi: "M-FLASH > с USB-накопителя",
      gigabyte: "Q-Flash > с USB-накопителя",
      asrock: "Instant Flash > с USB-накопителя",
      biostar: "Update BIOS > с USB-накопителя",
    },
    description: "Обновление BIOS исправляет баги, добавляет поддержку новых CPU и повышает стабильность. Всегда скачивайте последнюю версию с сайта производителя материнской платы.",
    recommended: "Обновляйтесь, если есть конкретная проблема или вы ставите новый CPU. Не обновляйте 'просто так' если всё работает.",
    risks: "Сбой при обновлении (выключение питания) может 'прошить' BIOS. Используйте UPS. Извлекайте USB-накопитель после обновления.",
  },
  {
    id: "bios_profiles",
    title: "Сохранение и загрузка профилей BIOS",
    icon: '<svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 21H5a2 2 0 01-2-2V5a2 2 0 012-2h11l5 5v11a2 2 0 01-2 2z"/><polyline points="17 21 17 13 7 13 7 21"/><polyline points="7 3 7 8 15 8"/></svg>',
    biosPaths: {
      asus: "Tool > ASUS User Profile > Save Profile / Load Profile",
      msi: "OC > Save Profile / Load Profile",
      gigabyte: "Save & Exit > Save Profiles / Load Profiles",
      asrock: "OC Tweaker > Save/Load OC Profile",
      biostar: "Save & Exit > Save Profile / Load Profile",
    },
    description: "Сохраняйте профили перед экспериментами. Создайте 'Stock' профиль (дефолт) и 'OC' профиль (с вашими настройками).",
    recommended: "Всегда сохраняйте 'Stock' профиль перед любыми изменениями. Можно сохранить до 8 профилей.",
    risks: "При проблемах загрузите сохранённый профиль через BIOS. Если BIOS не загружается — Clear CMOS вернёт дефолт.",
  },
];
